root: /eccube/html/
admin_dir: admin/
tpl: /eccube/html/user_data/packages/default/
admin_tpl: /eccube/html/user_data/packages/admin/
image_path: /eccube/html/upload/save_image/
root_dir: 'C:\xampp\htdocs\eccube'
root_urlpath: /eccube/html
template_code: custom
admin_route: admin
user_data_route: user_data
public_path: /html
public_path_realdir: 'C:\xampp\htdocs\eccube/html'
image_save_realdir: 'C:\xampp\htdocs\eccube/html/upload/save_image'
image_temp_realdir: 'C:\xampp\htdocs\eccube/html/upload/temp_image'
user_data_realdir: 'C:\xampp\htdocs\eccube/html/user_data'
block_default_realdir: 'C:\xampp\htdocs\eccube/src/Eccube/Resource/template/default/Block'
block_realdir: 'C:\xampp\htdocs\eccube/app/template/custom/Block'
template_default_realdir: 'C:\xampp\htdocs\eccube/src/Eccube/Resource/template/default'
template_default_html_realdir: 'C:\xampp\htdocs\eccube/html/template/default'
template_admin_realdir: 'C:\xampp\htdocs\eccube/src/Eccube/Resource/template/admin'
template_admin_html_realdir: 'C:\xampp\htdocs\eccube/html/template/admin'
template_realdir: 'C:\xampp\htdocs\eccube/app/template/custom'
template_html_realdir: 'C:\xampp\htdocs\eccube/html/template/custom'
template_temp_realdir: 'C:\xampp\htdocs\eccube/app/cache/eccube/template'
csv_temp_realdir: 'C:\xampp\htdocs\eccube/app/cache/eccube/csv'
plugin_realdir: 'C:\xampp\htdocs\eccube/app/Plugin'
plugin_temp_realdir: 'C:\xampp\htdocs\eccube/app/cache/plugin'
plugin_html_realdir: 'C:\xampp\htdocs\eccube/html/plugin'
admin_urlpath: /eccube/html/template/admin
front_urlpath: /eccube/html/template/custom
image_save_urlpath: /eccube/html/upload/save_image
image_temp_urlpath: /eccube/html/upload/temp_image
user_data_urlpath: /eccube/html/user_data
plugin_urlpath: /eccube/html/plugin
